net/connector/tcp: retry establishement
Distributed-EPFL/drop pull request #24
Opened 2021-05-11 15:31 UTC by tharvik

When using a TCPConnector, it bails out at the first error, which might be only temporary. This patch retry establishing the connection.

I tried using it direclty in `System::new`, but there was some issues with `F` not being `Copy`.
And why is it taking an `IntoIterator` and not a `Vec`? That's a bit cumbersome to use it (as I have to copy it when retrying the block).

2021-05-11 16:30 UTC, SonicFrog commented
I would rather have this as some sort of `Backoff` `Connector` than directly in any concrete connector

2021-05-11 16:46 UTC, SonicFrog requested changes

2021-05-11 16:46 UTC, SonicFrog commented on Cargo.toml
> +backoff = { version = "0.3.0", features = ["tokio"] }
```suggestion
backoff = { version = "0.3", features = ["tokio"] }
```

2021-05-11 16:46 UTC, SonicFrog commented on src/net/connector/tcp.rs
> +        backoff::future::retry(ExponentialBackoff::default(), || async {
This would be better off in a separate Backoff Connector that can use any other `Connector`

2021-05-12 12:01 UTC, SonicFrog commented
Just thought about it but having some companion trait for `Connector` would be nice too. Something along these lines would be cool

```rust
/// An extension trait for [`Connector`]s
///
/// [`Connector`]: self::Connector
pub trait ConnectorExt: Connector + Sized {
    fn retry(self) -> BackoffConnector<Self> {
        BackoffConnector::new(self)
    }

    fn resolve(self) -> Resolve<Self, Self::Candidate> {
        Resolve::new(self)
    }
}

impl<C> ConnectorExt for C where C: Connector {}
```

With this you could do someone like that 
```rust
let connector = TcpConnector::new(Exchanger::random()).retry();
```

2021-05-12 13:08 UTC, tharvik commented
> Just thought about it but having some companion trait for `Connector` would be nice too.

Indeed!

> ```rust
> pub trait ConnectorExt: Connector + Sized {
>     fn resolve(self) -> Resolve<Self, Self::Candidate> {
>         Resolve::new(self)
>     }
> }
> ```

Got it but why do you need `fn resolve`?

2021-05-12 13:37 UTC, SonicFrog commented
> And why is it taking an `IntoIterator` and not a `Vec`? That's a bit cumbersome to use it (as I have to copy it when retrying the block).

Flexibility, but there is no need for copies:

```rust 
let peers: Vec<(PublicKey, SocketAddr); // loaded from wherever
let connector = TcpConnector::new(exchanger);

let system = System::new_with_connector_zipped(&connector, peers.iter().copied()).await;

2021-05-17 11:29 UTC, SonicFrog approved these changes

2021-05-17 11:43 UTC, merged